refs #12 - Deployment HNZ
fledge-power/fledgepower-deployment pull request #13
Opened 2023-06-07 11:46 UTC by YmaIneo

2023-10-10 12:59 UTC, FlorentP42 approved these changes

2023-10-11 14:31 UTC, aklira requested changes

2023-10-11 14:31 UTC, aklira commented on s104-n104-ubuntu2004/fledge/fledge.dockerfile
Version fledge_2.1.0-803 is not available anymore. Need to update to latest version.

2023-10-13 09:55 UTC, FlorentP42 commented on sHNZ-n104-ubuntu2004/docker-compose.yml
> +      - "6001:6002"
```suggestion
      - "6001:6001"
      - "6002:6002"
```

2023-10-13 09:55 UTC, FlorentP42 commented on sHNZ-n104-ubuntu2004/fledge/fledge.dockerfile
> +EXPOSE 8081 8090 1995 8080 2404 2405
```suggestion
EXPOSE 8081 8090 1995 8080 2404 2405 6001 6002
```

2023-10-13 09:55 UTC, FlorentP42 commented on sHNZ-n104-ubuntu2004/docker-compose.yml
> +      - "8081:8081"
use 8090 here?

2023-10-16 07:58 UTC, FlorentP42 approved these changes

2023-10-17 09:34 UTC, aklira approved these changes

2023-10-17 09:34 UTC, merged